### ISSUE TITLE
Support GHC 7.8.4 and related base library

### ISSUE THREAD

**Issue by adinapoli** [adinapoli/ekg-prometheus-adapter#2]
cc @cdornan

**Comment by Mikolaj** [comment]
Isn't this fixed already? However, updating deps to GHC 8.4.4. would be welcome, in particular to newer prometheus package. :)

**Comment by Mikolaj** [comment]
@adinapoli: could you release this on Hackage? It compiles fine for me on GHC 8.4.4.

**Comment by adinapoli** [comment]
@Mikolaj Done!

**Comment by Mikolaj** [comment]
Thank you very much!
