### ISSUE TITLE
Doesn't compile with 8.6.4

### ISSUE THREAD

**Issue by Mikolaj** [adinapoli/ekg-prometheus-adapter#5]
@adinapoli : would you give me rights for https://hackage.haskell.org/package/ekg-prometheus-adapter so that I can make a Hackage revision bumping the `containers` dep? I've tested locally with `cabal test --constraint="containers==0.6.0.1" --allow-newer` that it works fine.

**Comment by adinapoli** [comment]
@Mikolaj done!

**Comment by Mikolaj** [comment]
@adinapoli:  revised; thank you very much! Closing.
